src/Entity/Property.php
<?php

namespace App\Entity;

use App\Repository\PropertyRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;
use Cocur\Slugify\Slugify;
use Symfony\Component\Validator\Constraints as Assert;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\HttpFoundation\File\File;
use Vich\UploaderBundle\Mapping\Annotation as Vich;

#[ORM\Entity(repositoryClass: PropertyRepository::class)]
#[UniqueEntity('title')]
#[Vich\Uploadable]
class Property
{
    const HEAT = [
        0 => 'Electric',
        1 => 'Gaz'
    ];

    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    /**
     * 
     * @var File|null 
     */
    #[Vich\UploadableField(mapping: "property_image", fileNameProperty: "imageName", size:"imageSize")]
    private ?File $imageFile = null;

    /**
     * this property represents the name of image file uploaded by VichUploader in the database.
     * @var string|null 
     */
    #[ORM\Column(length: 255, nullable: true)]
    // #[Assert\Image(mimeTypes:['image/jpg'])]
    private ?string $imageName = null;

    #[ORM\Column(nullable: true)]
    private ?int $imageSize = null;

    #[ORM\Column(nullable: true)]
    private ?\DateTimeImmutable $updatedAt = null;

    #[Assert\Length(min: 10, minMessage: "Name is too short" )]
    #[ORM\Column(length: 255)]
    private ?string $title = null;

    #[ORM\Column(type: Types::TEXT, nullable: true)]
    private ?string $description = null;

    #[Assert\Range(min: 10, max:400 )]
    #[ORM\Column]
    private ?int $surface = null;

    #[Assert\Range(min: 1, max:20 )]
    #[ORM\Column]
    private ?int $rooms = null;

    #[Assert\Range(min: 1, max:30 )]
    #[ORM\Column]
    private ?int $bedrooms = null;
    
    #[Assert\Range(min: 1, max:10 )]
    #[ORM\Column]
    private ?int $floor = null;

    #[ORM\Column]
    private ?int $price = null;

    #[ORM\Column]
    private ?int $heat = null;

    #[ORM\Column(length: 255)]
    private ?string $city = null;

    #[ORM\Column(length: 255)]
    private ?string $address = null;

    #[Assert\Regex("/^[0-9]{5}$/")]
    #[ORM\Column(length: 255)]
    private ?string $postal_code = null;

    #[ORM\Column(options: ['default' => 'false'])]
    private ?bool $sold = false;

    #[ORM\Column]
    private ?\DateTimeImmutable $created_at = null;

    #[ORM\ManyToMany(targetEntity: Option::class, inversedBy: 'properties')]
    private Collection $options;

    #[ORM\ManyToOne(inversedBy: 'properties')]
    private ?PropertyTag $tag = null;

    #[ORM\Column(nullable: true)]
    private ?float $latitude = null;

    #[ORM\Column(nullable: true)]
    private ?float $longitude = null;

    public function __construct()
    {
        $this->created_at = new \DateTimeImmutable();
        $this->options = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function getSlug(?string $string = null): ?string{
        if($string){
            return (new Slugify())->slugify($string);
        }
        return (new Slugify())->slugify($this->title);
    }

    public function setTitle(string $title): static
    {
        $this->title = $title;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(?string $description): static
    {
        $this->description = $description;

        return $this;
    }

    public function getSurface(): ?int
    {
        return $this->surface;
    }

    public function setSurface(int $surface): static
    {
        $this->surface = $surface;

        return $this;
    }

    public function getRooms(): ?int
    {
        return $this->rooms;
    }

    public function setRooms(int $rooms): static
    {
        $this->rooms = $rooms;

        return $this;
    }

    public function getBedrooms(): ?int
    {
        return $this->bedrooms;
    }

    public function setBedrooms(int $bedrooms): static
    {
        $this->bedrooms = $bedrooms;

        return $this;
    }

    public function getFloor(): ?int
    {
        return $this->floor;
    }

    public function setFloor(int $floor): static
    {
        $this->floor = $floor;

        return $this;
    }

    public function getPrice(): ?int
    {
        return $this->price;
    }

    public function getFormatedPrice(): ?string{
        return number_format($this->price, 0, '', ' ');
    }

    public function setPrice(int $price): static
    {
        $this->price = $price;

        return $this;
    }

    public function getHeat(): ?int
    {
        return $this->heat;
    }

    public function getTypeHeat(?int $heat = null): ?string{
        if($heat){
            return self::HEAT[$heat];
        }
        return self::HEAT[$this->heat];
    }

    public function setHeat(int $heat): static
    {
        $this->heat = $heat;

        return $this;
    }

    public function getCity(): ?string
    {
        return $this->city;
    }

    public function setCity(string $city): static
    {
        $this->city = $city;

        return $this;
    }

    public function getAddress(): ?string
    {
        return $this->address;
    }

    public function setAddress(string $address): static
    {
        $this->address = $address;

        return $this;
    }

    public function getPostalCode(): ?string
    {
        return $this->postal_code;
    }

    public function setPostalCode(string $postal_code): static
    {
        $this->postal_code = $postal_code;

        return $this;
    }

    public function isSold(): ?bool
    {
        return $this->sold;
    }

    public function setSold(bool $sold): static
    {
        $this->sold = $sold;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeImmutable
    {
        return $this->created_at;
    }

    public function setCreatedAt(\DateTimeImmutable $created_at): static
    {
        $this->created_at = $created_at;

        return $this;
    }

    // custom function
    public function getTruncatedString(string $value, int  $length): ?string{
        if(strlen($value) >= $length){
            return substr($value, 0, $length) . '...';
        }else{
            return $value;
        }
    }

    /**
     * @return Collection<int, Option>
     */
    public function getOptions(): Collection
    {
        return $this->options;
    }

    public function addOption(Option $option): static
    {
        if (!$this->options->contains($option)) {
            $this->options->add($option);
            $option->addProperty($this);
        }

        return $this;
    }

    public function removeOption(Option $option): static
    {
        if ($this->options->removeElement($option)) {
            $option->removeProperty($this);
        }

        return $this;
    }


    /**
     * Get the value of imageFile
     */ 
    public function getImageFile()
    {
        return $this->imageFile;
    }

    /**
     * Set the value of imageFile
     *
     * @return  self
     */ 
    public function setImageFile($imageFile)
    {
        $this->imageFile = $imageFile;

        if (null !== $imageFile) {
            // It is required that at least one field changes if you are using doctrine
            // otherwise the event listeners won't be called and the file is lost
            $this->updatedAt = new \DateTimeImmutable();
        }
        return $this;
    }

    /**
     * Get the value of imageName
     */ 
    public function getImageName()
    {
        return $this->imageName;
    }

    /**
     * Set the value of imageName
     *
     * @return  self
     */ 
    public function setImageName($imageName)
    {
        $this->imageName = $imageName;

        return $this;
    }

    /**
     * Get the value of imageSize
     */ 
    public function getImageSize()
    {
        return $this->imageSize;
    }

    /**
     * Set the value of imageSize
     *
     * @return  self
     */ 
    public function setImageSize($imageSize)
    {
        $this->imageSize = $imageSize;

        return $this;
    }

    public function getTag(): ?PropertyTag
    {
        return $this->tag;
    }

    public function setTag(?PropertyTag $tap): static
    {
        $this->tag = $tap;

        return $this;
    }

    public function getLatitude(): ?float
    {
        return $this->latitude;
    }

    public function setLatitude(?float $latitude): static
    {
        $this->latitude = $latitude;

        return $this;
    }

    public function getLongitude(): ?float
    {
        return $this->longitude;
    }

    public function setLongitude(?float $longitude): static
    {
        $this->longitude = $longitude;

        return $this;
    }
}

src/Controller/PropertyController.php
<?php

namespace App\Controller;

use App\Entity\Property;
use App\Entity\PropertySearch;
use App\Form\PropertySearchType;
use Doctrine\ORM\EntityManagerInterface;
use Knp\Component\Pager\PaginatorInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Attribute\Route;

class PropertyController extends AbstractController
{
    /**
     * @var EntityManagerInterface
     */
    private $em;

    public function __construct(EntityManagerInterface $em)
    {
        $this->em = $em;
    }

    #[Route('/properties', name: 'property.index')]
    public function index(PaginatorInterface $panigator, Request $request): Response
    {
        // form search handler
        $search = new PropertySearch();
        $form = $this->createForm(PropertySearchType::class, $search);
        $form->handleRequest($request);

        if($form->isSubmitted() and $form->isValid()){
            // code...
        }

        $repo = $this->em->getRepository(Property::class);
        $query = $repo->findAllVisibleQuery($search);
        $propertiesPagination = $panigator->paginate(
            $query,
            $request->query->getInt('page', 1),
            12
        );
        
        return $this->render('property/index.html.twig', [
            'controller_name' => 'PropertyController',
            'properties' => $propertiesPagination,
            'nb_results' => $propertiesPagination->getTotalItemCount(),
            'current_menu' => 'properties',
            'form' => $form->createView()
        ]);
    }

    #[Route('/properties/{slug}-{id}', name: 'property.show', requirements: ['slug' => "[A-Za-z0-9\-]*"])]
    public function show($slug, $id, Property $property): Response
    {
        // security check for fake slugs
        if($slug !== $property->getSlug()){
            return $this->redirectToRoute('property.show', [
                    'slug' => $property->getSlug(), 
                    'id' => $property->getId()
                ], 301);
        }
        $result = $this->em->getRepository(Property::class)->find($id);
        return $this->render('property/show.html.twig', [
            'controller_name' => 'PropertyController',
            'property' => $result,
        ]);
    }
}

templates/property/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Properties{% endblock %}

{% block body %}
    
    <div class="form-search-content mt-[3rem] mb-[4rem] desktop-width">
        <span id="open-filters" class="sm:hidden flex gap-2 cursor-pointer w-[5rem] ms-auto">
            <svg fill="#1c5588" width="25px" viewBox="0 0 32 32" version="1.1" xmlns="http://www.w3.org/2000/svg">
                <title>filter</title>
                <path d="M30 6.749h-28c-0.69 0-1.25 0.56-1.25 1.25s0.56 1.25 1.25 1.25v0h28c0.69 0 1.25-0.56 1.25-1.25s-0.56-1.25-1.25-1.25v0zM24 14.75h-16c-0.69 0-1.25 0.56-1.25 1.25s0.56 1.25 1.25 1.25v0h16c0.69 0 1.25-0.56 1.25-1.25s-0.56-1.25-1.25-1.25v0zM19 22.75h-6.053c-0.69 0-1.25 0.56-1.25 1.25s0.56 1.25 1.25 1.25v0h6.053c0.69 0 1.25-0.56 1.25-1.25s-0.56-1.25-1.25-1.25v0z"></path>
            </svg>
            <span class="text-lg text-main">Filters</span>
        </span>
        <div class="content w-full sm:block hidden">
            <div class="sm:hidden flex justify-end mb-8">
                <i id="close-filters" class="fa fa-xmark border-[3px] border-white text-white p-[15px] cursor-pointer hover:text-red-700"></i>
            </div>
            {{ form_start(form) }}
                {{ form_row(form.maxPrice) }}
                {{ form_row(form.minSurface) }}
                <div class=" sm:w-[27%] w-full">
                    {{ form_rest(form) }}
                </div>
                <button type="submit" class="btn-search">Search</button>
            {{ form_end(form) }}
        </div>
    </div>

    <div class="head-properties desktop-width">
        <h1 class="text-3xl font-bold my-8 pt-serif">Found <span class="text-main">{{nb_results}}</span> Properties for sell & rent</h1>
    </div>
    
    <section class="properties-section desktop-width">
        <div class="content mb-4 flex flex-wrap gap-12 justify-center">
            {% for property in properties %}
                {% include '_files/property-grid.html.twig' with {'property':property} %}
            {% endfor %}
        </div>
        <div class="navigation flex justify-center mt-[4rem] mb-[7rem]">
            {{ knp_pagination_render(properties) }}
        </div>
    </section>

{% endblock %}

templates/property/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}{{ property.title }} {% endblock %}

{% block stylesheets %}
    {{ encore_entry_link_tags('app') }}
     <link rel="stylesheet" href="https://unpkg.com/leaflet@1.9.4/dist/leaflet.css"
     integrity="sha256-p4NxAoJBhIIN+hmNHrzRCf9tD/miZyoHS5obTRR9BMY="
     crossorigin=""/>
{% endblock %}

{% block body %}

<section class="property-section property-width">
    <div class="content mt-[5rem] mb-[10rem]">
       <div class="top flex sm:flex-row flex-col gap-8">
            <div class="img relative max-w-[550px] w-full">
                {% if vich_uploader_asset(property, 'imageFile') is null %}
                    <img class="w-full" src="{{ 'http://localhost:8000/images/properties/empty.jpg'}}" alt="property">
                {% else %}
                    <img class="w-full" src="{{ vich_uploader_asset(property, 'imageFile') }}" alt="property">
                {% endif %}

                {% if property.tag  %}
                    <div class="ribbon show pt-serif">
                        {{ property.tag }}
                    </div>
                {% endif %}
            </div>
            <div class="infos">
                <h1 class="property-title">{{ property.title }}</h1>
                <h2 class="text-[1.5rem] mt-[10px] font-bold"> {{ property.rooms }} Rooms - {{ property.surface }} m² - {{ property.city }} <br> {{ property.address }}</h2>
                
                <h3 class="text-main text-[3rem] font-bold mt-[10px] ">{{ property.formatedPrice }} $</h3>
                <button type="button" class="btn-submit" id="btn-booking">Book now</button>
            </div>
       </div>
       <div class="techniques flex sm:flex-row flex-col">
            <div class="tech-1 sm:w-1/2 w-full">
                <h4 class="font-bold text-[2rem] text-main mt-8 mb-4">Details</h4>
                <table class="tech-table" border="0">
                    <tr>
                        <td>City</td>
                        <td class="font-semibold">{{ property.city }}</td>
                    </tr>
                    <tr>
                        <td>Address</td>
                        <td class="font-semibold">{{ property.address }}</td>
                    </tr>
                    <tr>
                        <td>living space</td>
                        <td class="font-semibold">{{ property.surface }} m²</td>
                    </tr>
                    <tr>
                        <td>Rooms</td>
                        <td class="font-semibold">{{ property.rooms }}</td>
                    </tr>
                    <tr>
                        <td>Bed rooms</td>
                        <td>{{ property.bedRooms }}</td>
                    </tr>
                    <tr>
                        <td>Floor</td>
                        <td class="font-semibold">{{ property.floor }}</td>
                    </tr>
                    <tr>
                        <td>Heating</td>
                        <td class="font-semibold">{{ property.typeHeat }}</td>
                    </tr>
                </table>
            </div>
            <div class="tech-2">
                <h4 class="font-bold text-[2rem] text-main mt-8 mb-4">Specificities</h4>
                <div class="options flex flex-col gap-[10px]">
                    {% if property.options  is not empty  %}
                        {% for option in property.options %}
                            <p class="property-option">{{ option }} </p>
                        {% endfor %}
                    {% else %}
                       <p class="text-lg text-gray-500">Specificities not found</p>
                    {% endif %}
                    
                </div>
            </div>
        </div>
        <div class="map-section">
            <span id="lat" data-latitude="{{ property.latitude }}"></span>
            <span id="long" data-longitude="{{ property.longitude }}"></span>
            <h4 class="font-bold text-center text-[2rem] text-main mt-[4rem] mb-4">Location</h4>
            <div class="map-content">
                <p id="network-error" class=" text-center text-gray-600 text-lg">Map not available due to Network <span class="text-red-700">ERROR</span></p>
                <div id="map">
                </div>
            </div>
        </div>
    </div>
</section>

<div id="booking-modal" class="hidden fixed top-0 left-0 w-full h-full  bg-[#1c558896] z-10">
    <div class="modal-content flex justify-center items-center w-full h-full p-4">
        <div class="content bg-white max-w-[500px] w-full mx-auto px-3 flex gap-4 flex-col justify-center items-center border-2 rounded-md p-4">
            <div class="rounded-[50%] h-[100px] w-[100px] bg-green-700 p-4 flex justify-center items-center">
                <i class="fa-solid fa-check text-white text-[32px]"></i>
            </div>
            <p class="text-gray-500 text-sm">Booking Ref. USA-BR-45782JU451152K-DELIVERY</p>
            <h4 class="text-main text-[26px] font-semibold pt-serif text-center">You succesfully created your Booking.</h4>
            <p class="sm:text-[21px] text-lg text-back">one of our agents will contact you within the next 24 hours</p>
        </div>
    </div>
</div>

{% endblock %}

{% block javascripts %}
    {{ encore_entry_script_tags('app') }}
    {% block importmap %}
        {{ importmap('app') }}
    {% endblock %}
    <!-- Make sure you put this AFTER Leaflet's CSS -->
 <script src="https://unpkg.com/leaflet@1.9.4/dist/leaflet.js"
     integrity="sha256-20nQCchB9co0qIjJZRGuk2/Z9VM+kNiyxNV1lvTlZBo="
     crossorigin="" defer></script>
     
{% endblock %}